name = "cereal"
description = "A simple blog theme designed for personal blogs"
# An optional tags to allow quick search
tags = []
license = "BSD 2-Clause License"
homepage = "https://github.com/antipeth/cereal"
# The minimum version of Zola required
min_version = "0.22.1"
# An optional live demo URL
demo = ""

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "antipeth"
homepage = "https://blog.0pt.icu"
